export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SAGA = "ADD_TO_CART_SAGA";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const REMOVE_TO_CART_SAGA = "REMOVE_TO_CART_SAGA";

export const GET_TODO_START = "GET_TODO_START";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";

export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const GET_TASK_START = "GET_TASK_START";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_ERROR = "GET_TASK_ERROR";

export const ADD_TASK_START = "ADD_TASK_START";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const UPDATE_TASK_STATUS_START = "UPDATE_TASK_STATUS_START";
export const UPDATE_TASK_STATUS_SUCCESS = "UPDATE_TASK_STATUS_SUCCESS";
export const UPDATE_TASK_STATUS_ERROR = "UPDATE_TASK_STATUS_ERROR";
